### ISSUE TITLE
How long does this usually take on an A100?

### ISSUE THREAD

**Issue by utimcraig** [martinpacesa/BindCraft#25]
To find binders for a well folded, 25kDa soluble domain enzyme?  How long should I expect this to run?  Is there some point where it automatically stops?

**Comment by LennartNickel** [comment]
One quick note on that: Every target and cluster/workstation is different, which is why its hard to predict how long it will take to get enough passing designs! For some targets, you will get a good amount of passing designs in some hours (for us e.g. PDL1, EGFR). However, this is a rare case. Usually sampling overnight on a few GPUs (on our systems) is sufficient to get enough designs to make a selection for experimental validation. However, there are cases where you have to sample a lot more to get a few designs passing filters, and its not given that you find hits for every protein at all!

**Comment by nfloquet** [comment]
On local machines (local GPUs), to avoid memory problems, does it make sense to limit the structure of the target to the binder's expected pocket ?

**Comment by LennartNickel** [comment]
Generally yes, but be careful not to open the hydrophobic core too much as the binders will then be preferentially placed there. Unfortunately, for some proteins (especially some transporters, ion channels, GPCRs, etc.) that do not have a well-defined/separated extracellular domain or where the binding site is well integrated into the protein, it can be difficult to find a good starting point. In this case, it is worth doing some shorter test runs with different settings (especially different cropping, different hotspots) to find a working setup. It is not necessary to wait for a accepted designs during these test runs. Simply look at the sampled trajectories and check whether the desired binding mode is achieved.
