### ISSUE TITLE
How to resume the computation in the colab?

### ISSUE THREAD

**Issue by finexzhi** [martinpacesa/BindCraft#40]
I ran the computation to the 4th stage of "run BindCraft" . However, it was stopped because my computer went to sleep.

As such, I could not run the next step "consolidate and rank designs".

Is that anyway to resume the computation from where I left? Or I have to start over.

Thanks!

I am using colab pro+.

**Comment by martinpacesa** [comment]
Since the data is saved on your google drive, you can just start it again and as long as it points to the same output folder it will continue doing the designs. Note, the cosolidate and rank designs part will only start automatically once sufficient number of designs have passed the filters (100 by defualt). This can take a long time depending on your target size, generally you need to generate like 500-3000 trajectories to get 100 that pass the filters. However, if less is okay for you, then you can stop the design loop cell and just run consolidate and rank designs. You can also continue any time and consolidate again, the pipeline is designed in a way that you can always generate more designs and it does not "break" anything.

**Comment by finexzhi** [comment]
Thanks for the clarification. It is very clear now that the newly found hits were stored under the project folder. We can always run the software to search the sequence universe to find potentially better hits. I know this could be a random process. But when I start a new round of run, how can the software know which space it has already searched?

**Comment by martinpacesa** [comment]
Based on the filename, that's why we include the binder length and seed number which is what "roughly" determines the search space.
