### ISSUE TITLE
multi-chain receptor input & noncontinuous pdb truncating for memory efficient design

### ISSUE THREAD

**Issue by jbderoo** [martinpacesa/BindCraft#57]
Hi all,

Thank you very much for your hard work; this is a beautiful thing. I have two questions that I'm trying to address simultaneously.

1) I am trying to design a small binder (8-20 resi) into a pocket formed by a heterodimer. Assuming I had access to a large-memory GPU, how would I specify the hotspots a1, a2, a3 on chain A and b1, b2, b3 on chain B (panel A)?
2) Much of this heterodimer is unneccesary. I'd like to cut away large chunks of chain A and chain B, and provide BindCraft with, effectively, a shortened receptor (panel B) such that my workstation GPU (16 GB 4080) can handle this job. Chain A is continuous and easy to work with; the receptor surface of chain B is noncontinuous and has 3 separate chunks. In an effort to circumnavigate the issue in point 1, I combined this receptor into a single PDB (panel C) and renumbered it continuously and with a uniform chain ID. However, when I do this and design a binder against the new hotspots (orange residues, C), it significantly distorts the receptor, I think in an attempt to try and fold the receptor surface as if it was a single continuous protein. Panels D and E highlight one example of this happening, where the design is in light blue and the "hack-n-slash" receptor is in orange/white. Panel F highlights a second example of the exact same thing in purple. How might I fix the receptor surface such that:

    2.1) I'm providing BindCraft with only the essential receptor residues so that my GPU can process the job (a 16 GB 4080 can handle approximately a 60 resi system) without residue coordinate distortion?
    
    2.2) If I can't completely fix the residue coordinates in chain B (cyan, noncontinuous, panel B) can I break up chain B into chain B (6 resi long), chain C (7 resi long), and chain D (9 resi long), then specify several receptor chains and their respective hotspots on those chains in the input json file?
    
Thank you preemptively!

Kind regards,

Jacob

![rect12](https://github.com/user-attachments/assets/4db2bf8a-92f4-4f97-96ff-39fc1d608948)

**Comment by martinpacesa** [comment]
Hey Jacob,

The hotspots can be specified as 'A1,A4,A5,B2,B4,B9,B12' etc.

So the complex doesn't look too big, I personally would not cut it, because little pieces like that can still move and the movement might be too significant if not stabilised by the rest of the backbone. Unforunately the chunks you indicate are a bit too small to stabilise I think. Perhaps in your case it makes more sense to use RFdiffusion?

Alternatively, you can run it on the colab with colab pro and run it without trimming.

**Comment by jbderoo** [comment]
Hi Martin,

Thanks! I could have sworn I tried that before reaching out and it didn't work - very likely user error since it's running now. Thank you! 

I am in a fortunate position where I can experimentally test many many peptides (~1,000) - I would ideally like to test a myriad of the binder generation schemes that have come out. This is off topic w.r.t BindCraft, but after generating say 1,000 peptide backbones, when do you use ProteinMPNN and AlphaFold to verify the binders (similar to Sergey's colab notebook https://colab.research.google.com/github/sokrypton/ColabDesign/blob/v1.1.1/rf/examples/diffusion.ipynb) vs when do you use the dl_binder_design by Bennet (https://github.com/nrbennet/dl_binder_design)?

**Comment by martinpacesa** [comment]
As far as I know Bennett uses the same strategy of AF2 filtering, just not MPNN, but cannot say as I never used it. The only other good alternative right now is to use RFdiffusion+MPNN+AF2

**Comment by jbderoo** [comment]
Thank you for your input!

**Comment by kyleford8** [comment]
Coming back to this issue because it's related to one I've been curious about. For many proteins, the binding site of interest is made up of non continuous regions of the chain (ex. AAs 1-100, 200-300, and 900-1000). In PyMol you can select all residues within a certain distance of a feature (ex. select br. ChainA within 5.0 of ChainB), to generate a non continuous PDB file (see example pymol screenshot below) composed of a surface region. This functions as an input to BindCraft, and outputted target structures have good alignments to their full length "ground truth" experimentally derived structures. 

What are your thoughts regarding this strategy in general? It's very appealing in that the speedups can be significant. In contrast to the above user, I did not renumber the chains, the non continuous domains are larger, and did not observe major deviations from the "true" structure when modeling. I do have some concerns about how this might impact the validation rate down the line though (both experimentally and the in silico filtering).

<img width="401" alt="Screenshot 2024-10-23 at 10 19 18 AM" src="https://github.com/user-attachments/assets/ad893966-3dbe-4e7c-ab87-920bab400d63">

**Comment by martinpacesa** [comment]
It really depends. If you trim in a way that exposes protien cores, it's probably not gonna go down well and binders will try to cover it. But in principle there are many different ways one can generate the input structure and trimming like this is totally legit

**Comment by kyleford8** [comment]
Makes sense, thanks. Avoiding exposing the protein core was actually the original motivation (other than speed ups) for doing this. In that for some targets a continuous trim (ex. AAs 1-200) will get you the right surface, but expose a core. Whereas a non continuous trim using "within X" (ex. AAs 1-200, and also 300-350) will have both the surface and a partial section of the core behind it. Anecdotally this has helped keep my designed proteins at the right spot, as opposed to falling into a "pseudo pocket" created by the trimming.

**Comment by martinpacesa** [comment]
We've also done it, works fine :)
