### ISSUE TITLE
"AF2 interface predicted alignment error (i_pAE) (> 0.35) " why >?

### ISSUE THREAD

**Issue by mofatuzi** [martinpacesa/BindCraft#98]
In the preprint, one of the filter is "AF2 interface predicted alignment error (i_pAE) (> 0.35) "
Why ipAE > ?
Isn't the smaller the better for ipAE?  

> PAE (predicted aligned error): estimate of the error in the relative position and orientation between two tokens in the predicted structure. Higher values indicate higher predicted error and therefore lower confidence. For proteins and nucleic acids, PAE score is essentially the same as AlphaFold2, where the error is measured relative to frames constructed from the protein backbone. For small molecules and post-translational modifications, a frame is constructed for each atom from its closest neighbors from a reference conformer.

**Comment by martinpacesa** [comment]
It's just a typo, it is actuall < 0.35

**Comment by MrGao1997** [comment]
> In the preprint, one of the filter is "AF2 interface predicted alignment error (i_pAE) (> 0.35) " Why ipAE > ? Isn't the smaller the better for ipAE?
> 
> > PAE (predicted aligned error): estimate of the error in the relative position and orientation between two tokens in the predicted structure. Higher values indicate higher predicted error and therefore lower confidence. For proteins and nucleic acids, PAE score is essentially the same as AlphaFold2, where the error is measured relative to frames constructed from the protein backbone. For small molecules and post-translational modifications, a frame is constructed for each atom from its closest neighbors from a reference conformer.

do you kown how to calculate the iPAE? What is the formulas?

**Comment by martinpacesa** [comment]
It's the same as in the alphafold multimer paper, except it is normalised to 0-1 by dividing by 31

**Comment by MrGao1997** [comment]
Thanks for your reply. So if I predict a complex made of A-B chain, the formulas is averaging the PAEs contributed by A and B, then divided by 31?







---- Replied Message ----
| From | ***@***.***> |
| Date | 3/26/2025 16:56 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [martinpacesa/BindCraft] "AF2 interface predicted alignment error (i_pAE) (> 0.35) " why >? (Issue #98) |

It's the same as in the alphafold multimer paper, except it is normalised to 0-1 by dividing by 31

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

martinpacesa left a comment (martinpacesa/BindCraft#98)

It's the same as in the alphafold multimer paper, except it is normalised to 0-1 by dividing by 31

**Comment by martinpacesa** [comment]
pAEs of interface residues, then yes

**Comment by MrGao1997** [comment]
Thanks! 







---- Replied Message ----
| From | ***@***.***> |
| Date | 3/26/2025 17:09 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [martinpacesa/BindCraft] "AF2 interface predicted alignment error (i_pAE) (> 0.35) " why >? (Issue #98) |

pAEs of interface residues, then yes

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

martinpacesa left a comment (martinpacesa/BindCraft#98)

pAEs of interface residues, then yes
